namespace MyHome.Modules.Ledger.Contracts.Expenses;

/// <summary>
/// Whether an expense happens once or repeats, and how often.
/// </summary>
public enum ExpenseRecurrence
{
    /// <summary>One-off. No rule is created.</summary>
    Once = 0,

    /// <summary>Every month.</summary>
    Monthly = 1,

    /// <summary>Every two months.</summary>
    BiMonthly = 2,

    /// <summary>Every three months.</summary>
    Quarterly = 3,
}

/// <summary>
/// What the user says when they record an expense.
/// </summary>
/// <remarks>
/// An account, a category, an amount, a date and a description. Nothing about postings or signs:
/// that translation is the domain's job, which is what lets the form stay a form.
/// </remarks>
/// <param name="AccountId">Account the money leaves. Must be a real account.</param>
/// <param name="CategoryId">Category classifying the expense. Must be an expense category.</param>
/// <param name="Amount">
/// Amount spent, in major currency units and <b>positive</b>. The direction is implied by the
/// operation, not by the sign.
/// </param>
/// <param name="OccurredOn">Date the expense happened. Not necessarily today.</param>
/// <param name="Description">What it was. Required, because "-42 €" tells nobody anything.</param>
/// <param name="MemberId">Member it is attributed to, when it is not a shared expense.</param>
/// <param name="Recurrence">
/// Whether this expense repeats. Anything other than <see cref="ExpenseRecurrence.Once"/> also
/// creates a rule, so the household knows the expense is coming back. The entry for this month is
/// recorded either way.
/// </param>
/// <param name="ClientMutationId">
/// Idempotency key generated by the client. Sending the same one twice returns the entry recorded
/// the first time, so a retry after a dropped connection cannot duplicate the expense.
/// </param>
public sealed record RegisterExpenseRequest(
    Guid AccountId,
    Guid CategoryId,
    decimal Amount,
    DateOnly OccurredOn,
    string Description,
    Guid? MemberId = null,
    ExpenseRecurrence Recurrence = ExpenseRecurrence.Once,
    string? ClientMutationId = null);

/// <summary>
/// The expense as it was recorded, returned so the client can show it without refetching.
/// </summary>
/// <param name="Id">Identifier of the created entry.</param>
/// <param name="OccurredOn">Date it happened.</param>
/// <param name="Description">What it was.</param>
/// <param name="Amount">Amount spent, positive.</param>
/// <param name="Currency">Three-letter ISO 4217 code.</param>
/// <param name="AccountName">Account the money left.</param>
/// <param name="CategoryName">Category it was classified as.</param>
/// <param name="CategoryColorIndex">That category's tone, 1 to 10.</param>
/// <param name="Recurrence">How often it repeats, as recorded.</param>
/// <param name="WasAlreadyRegistered">
/// <see langword="true"/> when the request repeated a <c>ClientMutationId</c> already seen and
/// nothing new was created.
/// </param>
public sealed record RegisteredExpense(
    Guid Id,
    DateOnly OccurredOn,
    string Description,
    decimal Amount,
    string Currency,
    string AccountName,
    string CategoryName,
    int CategoryColorIndex,
    ExpenseRecurrence Recurrence,
    bool WasAlreadyRegistered);
